spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimension: 1536
  datasource:
    url: jdbc:postgresql://localhost:15439/vectorstore
    username: vectorstore
    password: vectorstore

documents:
  documentsToLoad:
    - https://stackoverflow.com/questions/73660191/effective-way-of-comparing-list-elements-in-java
    - https://stackoverflow.com/questions/322715/when-to-use-linkedlist-over-arraylist-in-java?page=2&tab=scoredesc
    - https://stackoverflow.com/questions/214741/what-is-a-stackoverflowerror
    - https://stackoverflow.com/questions/218384/what-is-a-nullpointerexception-and-how-do-i-fix-it